### PR TITLE
Fix flexbox display issue in IE11

### PR DESCRIPTION
**Pull request by lboynton**
Merge #158 first...

### CODE REVIEW

**Comment by lboynton** [comment]
Why hasn't it removed your commits :(

**Comment by asgrim** [comment]
You need to rebase

**Comment by lboynton** [comment]
Shouldn't need to!!12121123`dfsoksdfkmdfksam

**Comment by asgrim** [comment]
Assuming this is fixed, can't easily test myself, so will trust you :D

**Pull request merged**
